"""Add user profile columns

Revision ID: 468015503c24
Revises: eebd3a75f2a6
Create Date: 2026-07-03 11:47:18.225077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468015503c24'
down_revision: Union[str, None] = 'eebd3a75f2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('avatar_public_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('portfolio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'portfolio')
    op.drop_column('users', 'github')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_public_id')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
