"""Add Resume vault fields

Revision ID: 6cbfe3bc56f2
Revises: 1aca898085f9
Create Date: 2026-06-28 11:37:45.103063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cbfe3bc56f2'
down_revision: Union[str, None] = '1aca898085f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('display_name', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('original_filename', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('last_used', sa.DateTime(timezone=True), nullable=True))
    op.add_column('resumes', sa.Column('file_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'last_used')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'original_filename')
    op.drop_column('resumes', 'display_name')
    # ### end Alembic commands ###
