"""remove unused user columns

Revision ID: d5cc6123a17e
Revises: b9d9ea702e19
Create Date: 2026-07-03 13:19:24.696000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5cc6123a17e'
down_revision: Union[str, None] = 'b9d9ea702e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'anonymized_telemetry')
    op.drop_column('users', 'target_role')
    op.drop_column('users', 'experience_level')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'portfolio')
    op.drop_column('users', 'linkedin')
    op.drop_column('users', 'github')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('linkedin', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('portfolio', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('target_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('anonymized_telemetry', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('preferred_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
