"""Add Cloudinary columns to resume

Revision ID: eebd3a75f2a6
Revises: 30a8f8d0e739
Create Date: 2026-07-03 11:42:17.210439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eebd3a75f2a6'
down_revision: Union[str, None] = '30a8f8d0e739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('cloudinary_url', sa.String(length=500), nullable=True))
    op.add_column('resumes', sa.Column('public_id', sa.String(length=255), nullable=True))
    op.add_column('resumes', sa.Column('embedding_status', sa.String(length=50), nullable=True))
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'embedding_status')
    op.drop_column('resumes', 'public_id')
    op.drop_column('resumes', 'cloudinary_url')
    # ### end Alembic commands ###
