"""
Agent Pydantic schemas — typed state objects for LangGraph agents.

Every structured LLM output uses JSON mode + Pydantic validation (Rule #2).
"""

from typing import Annotated, TypedDict, List, Optional
from pydantic import BaseModel, Field, ConfigDict
import operator

class ATSBreakdown(BaseModel):
    model_config = ConfigDict(extra="ignore", strict=False) # ATS breakdown comes from external service, be lenient
    overall_score: int
    skill_score: int
    semantic_score: int
    experience_score: int
    quality_score: int
    explanation: str
    matched_skills: List[str] = Field(default_factory=list)
    missing_skills: List[str] = Field(default_factory=list)
    improvement_suggestions: List[str] = Field(default_factory=list)

# State component models
class CandidateProfile(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=False)
    skills: List[str] = Field(default_factory=list)
    projects: List[str] = Field(default_factory=list)
    experience_level: str = Field(default="", description="A concise, 1-3 word label (e.g., Fresher, Intern, Entry Level, Mid-Level, Senior, Lead, Executive)")
    experience_details: str = Field(default="", description="A detailed explanation of the candidate's education, internship duration, and reasoning for the experience level")
    gaps_vs_jd: List[str] = Field(default_factory=list)
    ats_breakdown: Optional[ATSBreakdown] = None

class Evaluation(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=False)
    question: str
    answer: str
    score: Optional[float] = None
    strengths: List[str] = Field(default_factory=list)
    weaknesses: List[str] = Field(default_factory=list)
    suggestion: str = ""
    ideal_answer: str = ""

class Question(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=False)
    text: str
    topic: str
    difficulty: int
    is_follow_up: bool = False
    
class SessionReport(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=False)
    score: float = 0.0
    technical_score: float = 0.0
    communication_score: float = 0.0
    problem_solving_score: float = 0.0
    readiness_label: str = ""
    summary: str = ""
    strong_topics: List[str] = Field(default_factory=list)
    weak_topics: List[str] = Field(default_factory=list)
    roadmap: List[str] = Field(default_factory=list)

# Main Graph State
class InterviewState(TypedDict):
    # Inputs
    resume_text: str
    jd_text: str
    
    # State generated by Analyzer
    candidate_profile: Optional[CandidateProfile]
    
    # Session state
    historical_scores: List[float]
    interview_history: List[str]
    current_difficulty: int
    questions: Annotated[List[Question], operator.add]
    next_question: Optional[Question]
    evaluations: Annotated[List[Evaluation], operator.add]
    
    # User input (set by API before resuming the graph)
    user_answer: Optional[str]
    
    # Control logic
    turn_count: int
    
    # Pending follow-up question from evaluator_coach (used by interviewer_smart)
    pending_followup_question: Optional[dict]
    
    # State generated by Coach
    report: Optional[SessionReport]
