"""
Merged Interviewer + Follow-up Agent

Replaces two separate agents (interviewer.py + follow_up.py) with smart routing:
- If evaluator_coach flagged needs_followup: use the pre-generated follow-up question
  (ZERO additional Gemini calls — the question was already generated by evaluator_coach)
- Otherwise: generate the next fresh question with one Gemini call (same as interviewer.py)

This reduces Gemini API calls from 2 to 1 per question generation.

Token optimization: The prompt uses only the distilled CandidateProfile fields
(skills, projects, experience_level, gaps_vs_jd) instead of the full raw resume
and JD texts, saving ~2300 input tokens per turn (~23,000 per interview).

Input state keys (from InterviewState):
    - pending_followup_question: dict | None (set by evaluator_coach_node)
    - candidate_profile: dict
    - current_difficulty: int (1-5, already updated by evaluator_coach)
    - turn_count: int
    - evaluations: list[dict]
    - questions: list[dict]

Output state keys:
    - next_question: dict
    - questions: [new question dict] (appended via operator.add)
    - turn_count: int (incremented)
    - current_difficulty: int (unchanged — already set by evaluator_coach)
    - pending_followup_question: None (cleared after use)
"""

import random
import time
from fastapi import HTTPException
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
from app.schemas.agent_schemas import InterviewState, Question
from app.tools.vector_store import chroma_retrieval_tool
from app.core.config import get_settings
from app.core.gemini_retry import with_retry
from app.core.logger import log_agent_execution

settings = get_settings()

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=settings.gemini_api_key,
    temperature=0.7,
    max_retries=0,  # We handle retries ourselves via with_retry
)

structured_llm = llm.with_structured_output(Question)

INTERVIEWER_PROMPT = """You are an expert technical interviewer conducting a mock interview.
Your goal is to formulate the next interview question for the candidate.

Candidate Profile (extracted from their resume and the target job description):
- Skills: {skills}
- Key Projects: {projects}
- Experience Level: {experience_level}
- Gaps vs JD: {gaps}

Current Difficulty Level: {difficulty}/5
Previous Questions Asked:
{history}

Here are some suggested topics/questions from our question bank matching the candidate's profile:
{retrieved_questions}

Task:
Formulate ONE clear, professional interview question.
You MUST make the question dynamic and highly tailored to the candidate's specific skills, projects, and gaps listed above.
For example, ask about a specific project they worked on, or probe a gap between their skills and the job requirements.

CRITICAL RULES:
1. DO NOT ask any question that is identical or highly similar to any question in the 'Previous Questions Asked' list.
2. DO NOT copy the suggested questions from the question bank. They are provided ONLY as a reference for the expected difficulty level. You must invent a completely NEW question based on the candidate's profile.
3. DO NOT ask generic textbook questions (e.g., "What is REST API?", "What is OOP?") unless absolutely necessary. Instead, contextualize it.
4. Output the question strictly according to the required schema."""

interviewer_prompt = ChatPromptTemplate.from_messages([
    ("system", INTERVIEWER_PROMPT),
    ("human", "Generate the next question."),
])

chain = interviewer_prompt | structured_llm


async def interviewer_smart_node(state: InterviewState) -> dict:
    """Smart interviewer: uses pre-generated follow-up if available, otherwise generates fresh question."""
    turn = state.get("turn_count", 0) + 1
    current_diff = state.get("current_difficulty", 1)
    pending_followup = state.get("pending_followup_question")

    # --- Path A: Follow-up question (ZERO extra Gemini calls) ---
    if pending_followup:
        print(f"InterviewerSmart: Using pre-generated follow-up question (turn {turn})")
        followup_q = Question(**pending_followup)
        followup_q.is_follow_up = True
        return {
            "next_question": followup_q.model_dump(),
            "questions": [followup_q.model_dump()],
            "turn_count": turn,
            "pending_followup_question": None,
        }

    # --- Path B: Fresh question (1 Gemini call) ---
    print(f"InterviewerSmart: Generating fresh question (turn {turn}, difficulty {current_diff}/5)...")

    profile = state.get("candidate_profile")
    skills = profile.get("skills", []) if profile else []

    # Build history string to avoid repeat questions
    asked_questions = state.get("questions", [])
    history_texts = [
        q.get("text", "") if isinstance(q, dict) else getattr(q, "text", "")
        for q in asked_questions
    ]
    history_str = "\n".join(f"- {text}" for text in history_texts) if history_texts else "None"

    # Retrieve seed questions from ChromaDB (zero AI calls — local vector search)
    topics = skills if skills else ["general"]
    retrieved = chroma_retrieval_tool(topics=topics, max_difficulty=current_diff, k=3)
    retrieved_str = (
        "\n".join(f"- [{q['topic']} Diff:{q['difficulty']}] {q['text']}" for q in retrieved)
        if retrieved else "No exact matches found."
    )

    try:
        start_time = time.time()
        question: Question = await with_retry(
            chain.ainvoke,
            {
                "skills": ", ".join(skills) if skills else "Not provided",
                "projects": ", ".join(profile.get("projects", [])) if profile else "Not provided",
                "experience_level": profile.get("experience_level", "Unknown") if profile else "Unknown",
                "gaps": ", ".join(profile.get("gaps_vs_jd", [])) if profile else "None identified",
                "difficulty": current_diff,
                "history": history_str,
                "retrieved_questions": retrieved_str,
            }
        )
        exec_time = time.time() - start_time
        log_agent_execution(
            session_id="N/A",
            agent_name="Interviewer Smart",
            execution_time=exec_time,
            model="gemini-2.5-flash",
            success=True,
            final_status="OK"
        )
    except HTTPException as e:
        log_agent_execution(
            session_id="N/A",
            agent_name="Interviewer Smart",
            execution_time=time.time() - start_time if 'start_time' in locals() else 0,
            model="gemini-2.5-flash",
            success=False,
            final_status=f"{e.status_code} {e.detail.get('error', 'ERROR') if isinstance(e.detail, dict) else e.detail}"
        )
        raise e
    except Exception as e:
        log_agent_execution(
            session_id="N/A",
            agent_name="Interviewer Smart",
            execution_time=time.time() - start_time if 'start_time' in locals() else 0,
            model="gemini-2.5-flash",
            success=False,
            final_status=f"500 UNKNOWN_ERROR: {str(e)}"
        )
        print(f"InterviewerSmart Error (Fallback triggered): {e}")

        fallback_candidates = [q for q in retrieved if q["text"] not in history_texts]
        if fallback_candidates:
            chosen = random.choice(fallback_candidates)
            question = Question(text=chosen["text"], topic=chosen["topic"], difficulty=chosen["difficulty"])
        else:
            hardcoded = [
                "Could you describe a challenging project you worked on recently and the technical decisions you made?",
                "How do you ensure your code is scalable and maintainable in a production environment?",
                "Describe a time you had to learn a new technology quickly to meet a deadline.",
                "What is your approach to testing and debugging complex distributed systems?",
                "Can you explain a time when you disagreed with a technical decision made by your team?",
                "Tell me about a time you had to optimize the performance of an application.",
                "How do you stay updated with the latest technologies and industry trends?",
                "Describe a situation where you had to troubleshoot a difficult bug in production.",
                "What are the most important principles of writing clean code in a collaborative team?",
                "Walk me through your process of designing a new feature from scratch.",
            ]
            available = [q for q in hardcoded if q not in history_texts]
            question = Question(
                text=random.choice(available) if available else hardcoded[0],
                topic="General",
                difficulty=current_diff,
            )

    return {
        "next_question": question.model_dump(),
        "questions": [question.model_dump()],
        "turn_count": turn,
        "current_difficulty": current_diff,
        "pending_followup_question": None,
    }
